# Generated by Django 5.0.6 on 2024-08-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='account',
        ),
    ]
